### ISSUE TITLE
How many people are currently using Staticman?

### ISSUE THREAD

**Issue by arnabwahid** [eduardoboucas/staticman#111]
@eduardoboucas How many active installs of Staticman is there as of now?

**Comment by eduardoboucas** [comment]
It's hard to tell. The npm barely gets any downloads, because most people just use the public instance and we don't collect much data from it. The best way to get an idea of the number of entries being processed is by looking at the [staticmanapp bot profile](http://github.com/staticmanapp), which shows ~11,000 entries in the last year.
