### ISSUE TITLE
Cannot GET

### ISSUE THREAD

**Issue by pgyogesh** [eduardoboucas/staticman#185]
Step 1: OK
Step 2: Done
 
Step 3:
Cannot GET /v2/entry/pgyogesh/blog/master/

My Repo: github.com/pgyogesh/blog

**Comment by garfieldmoore** [comment]
I think you may have the same issue I did.  See my closed issue #186;

I think you need to add 'comments' onto the url you are posting to like I did.  

It wasn't clear to me that the final optional part of the url is the name of the top level property in the yaml file.

**Comment by artipedia** [comment]
How to fix error like this..

success":false,"rawError":{"code":404,"status":"Not Found","message":"{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/repos/contents/#get-contents\"}"},"errorCode":"GITHUB_READING_FILE"}

 Thank you for your help..

**Comment by VincentTam** [comment]
Hi, this is the maintainer of @staticmanlab, a [public GitLab instance](https://gitlab.com/staticmanlab).  Maybe it's quite late, but I'm posting here so that others know the reason for this error.

@pgyogesh You have to POST to the `/entry` endpoint instead of GET.

@ArtiPedia From the error code 404, it seems that the URL in your HTML `<form>` `action` has been mistaken.  It would be better if you include URL's of your site and its source.

References:

1. [*Staticman Repo Setup Errors*](https://vincenttam.gitlab.io/post/2018-12-25-staticman-repo-setup-errors/).
2. Staticman v3 API scheme in #219

**Comment by alexwaibel** [comment]
This appears to have been answered by Vincent. Closing.
