### ISSUE TITLE
Is there a way I can use Staticman with images?

### ISSUE THREAD

**Issue by ghost** [eduardoboucas/staticman#248]
I swear I saw a line of text saying that user generated images could now be used with Staticman. Is this true or did I misread something?

PS; Could you please make a version of staticman for Gitlab?

**Comment by robinmoussu** [comment]
@VincentTam was able to do it on his [gitlab test](https://gitlab.com/VincentTam/test-hugo-staticman), as you can see in his [testing post](https://vincenttam.gitlab.io/test-hugo-staticman/posts/test-staticman/), but I wasn't able to do the same.

**Comment by VincentTam** [comment]
> Could you please make a version of staticman for Gitlab?

Yes, I did, in response to https://github.com/eduardoboucas/staticman/pull/219#issuecomment-417657297.  What's more?  Due to [demand for Staticman on Framagit](https://framagit.org/Bridouz/bridouz.frama.io/commit/7dadae4e55d0d232082dc8cae2f357057de05cf8), I've deployed [another public GitLab instance for Framagit](https://vincenttam.gitlab.io/post/2018-12-24-staticman-on-framagit/).

![Framagit and Staticman](https://vincenttam.gitlab.io/img/staticmanlab-frama.svg)

* * *

To respond to the prompt in the title, yes in a weak sense.  However, I think the response is negative _au sensu stricto_.  I'm _not_ sure if the current Staticman API can handle binary data---of course, you can always encode it in base64.

In the linked demo post that @robinmoussu has brought up, it's simply a Markdown syntax referring to an image that I've uploaded to my GitLab Pages _in advance_.  If you really need images, I would recommend Stack Exchange's way.  Upload them to a 3rd party image host first, then post their URL in the static comments written in Markdown.

P.S. Please [avoid hot linking](http://altlab.com/hotlinking.html) when using images from other sites.  When you use an image from an external server, provided that you have the right to reuse that image, make a copy in another image host (preferably your domain) and use the URL for your copied image.  Big sites like GitHub, Stack Exchange, big Discourse forums can automate this.

**Comment by VincentTam** [comment]
Updated answer: I've to correct my response for the strict sense, after [my recent test comment](https://framagit.org/staticman-gitlab-pages/huginn/merge_requests/23) on [my demo Huginn + Framagit + Staticman site](https://staticman-gitlab-pages.frama.io/huginn/posts/seconde-post/).

![Screenshot_2019-06-26 Seconde Post – Huginn + Framagit + Staticman](https://user-images.githubusercontent.com/5748535/60161873-a1939c80-97f8-11e9-9b99-5825a8536336.png)
Image: My demo Huginn + Framagit + Staticman site with

1. international language support
2. nested comments
3. base64 encoded image

You may try [encoding images into base64](https://stackoverflow.com/questions/1207190/embedding-base64-images), even though the encoded string is often larger than the binary image in terms of file size.
