### ISSUE TITLE
Staticman self-hosted on AWS S3 or Google Cloud Storage bucket

### ISSUE THREAD

**Issue by ghost** [eduardoboucas/staticman#257]
To self-host staticman (with or without Docker), would it be possible to do this on 
AWS S3 storage bucket or Google cloud storage?

**Comment by VincentTam** [comment]
It's _impossible_ for the proposed services to _dynamically_ respond to GET requests to the `/encrypt` endpoints.

**Comment by donaldboulton** [comment]
Staticman died

**Comment by VincentTam** [comment]
@donaldboulton If you're referring to @staticmanapp, then I'm pleased of [its rebirth](https://github.com/eduardoboucas/staticman/issues/243#issuecomment-453754860) because of users who appreciate that.  I'm not a fan of GitHub though.

If you're referring to the _Node.js app_, then https://github.com/donaldboulton/DWB/pull/40 is a good reminder of Staticman's GitLab support, which has been available for four months on GitLab.com.  You may consult https://vincenttam.gitlab.io/bhdemo ([Source](https://gitlab.com/vincenttam/bhdemo)) for a demo site.  This example has been well-received by math lovers on [Math.Meta.SE](https://math.meta.stackexchange.com/q/6534/290189).

P.S. [Another Staticman API instance on Framagit](https://framagit.org/staticman-gitlab-pages) is live.  I've unintentionally discovered that the build time for GitLab Pages on Framagit is _half_ of that on GitLab.com.

**Comment by alexwaibel** [comment]
As I understand it, this user wants the easiest way to host a private instance. From what I've seen Heroku is by far the simplest method.
