### ISSUE TITLE
Endpoint for repositories within an organization

### ISSUE THREAD

**Issue by richardrobberse** [eduardoboucas/staticman#273]
I'm trying to give staticman access to my repository, I've added staticman as a collaborator.
Next step is to perform a handshake with the URL below:
https://api.staticman.net/v2/connect/{your GitHub username}/{your repository name}

In my case, my organization is called 'bcondevops' and the repository is called bcondevops.github.io.
When I try to call the endpoint I get back 'Invocation not found'
I've tried both the v1 and the v2 endpoint.

**Comment by onwingslikeeagles** [comment]
Hello @richardrobberse,

As referenced in issue #227, people using Staticman have now went to using v3 of the tool, which is a GitHub application. Follow the steps within this comment [#243](https://github.com/eduardoboucas/staticman/issues/243#issuecomment-453754860) . **Note:** He has updated the tool to production, so use _api.staticman.net_ as the URL instead of _dev..._. 

Hope this helps.

**Comment by VincentTam** [comment]
This is a duplicate of #227.

**Comment by alexwaibel** [comment]
Closed as duplicate of #227
