### ISSUE TITLE
How to setup Staticman with GitHub and Zeit Now

### ISSUE THREAD

**Issue by BloggerBust** [eduardoboucas/staticman#291]
Hi Everyone!

I published a series on setting up [Staticman with GitHub and Zeit Now](https://bloggerbust.ca/series/staticman-with-github-and-zeit-now/). I hope this helps someone. Let me know what you think.

Cheers!

Trevor

**Comment by BloggerBust** [comment]
@eduardoboucas If you like the idea of Zeit Now support in Staticman, then I would be happy to make a pull request. Let me know.

**Comment by eduardoboucas** [comment]
For sure, that sounds great!

**Comment by VincentTam** [comment]
In the first part of the linked series, there's [a section about adding SSH keys](https://bloggerbust.ca/post/staticman-with-github-and-zeit-now/#comment-submitted#create-a-github-ssh-key-for-the-bot-account).  Nonetheless, according to https://github.com/eduardoboucas/staticman/issues/244#issuecomment-451704185, a PEM key is needed instead of an SSH key.

In addition, [GitLab EE docs](https://docs.gitlab.com/ee/ssh/#ed25519-ssh-keys) recommend using ED25519 instead of RSA.

> ED25519 SSH keys
Following best practices, you should always favor ED25519 SSH keys, since they are more secure and have better performance over the other types.
>
>ED25519 SSH keys were introduced in OpenSSH 6.5, so any modern OS should include the option to create them. If for any reason your OS or the GitLab instance you interact with doesn’t support ED25519, you can fallback to RSA.


See also:

1. PR #256
2. [*Which one is better: elliptic curve cryptography or RSA algorithm and why?* - Quora](https://www.quora.com/Which-one-is-better-elliptic-curve-cryptography-or-RSA-algorithm-and-why)

**Comment by BloggerBust** [comment]
Thank you for the information on SSH key standards and for the link on elliptic curve cryptography. Well, I am aware of elliptic curve cryptography and the advantages that it has over public key cryptography, I am behind on the latest encryption standards and need to commit some time updating my knowledge in this area.

**Comment by jimmyangel** [comment]
@BloggerBust I was able to follow your guide successfully until (and including) the "connect" part where the bot account accepts the collaborator invitation. Unfortunately, I have not been able to post comments since I am getting a 500 error without any details on the response or in the logs. I am puzzled, since I had v2 working with the staticman service before it went bad, so the client code should be ok (with the only change being the endpoint). Any hints as to where to begin looking? Thanks.

**Comment by VincentTam** [comment]
I think the guide needs to be updated with v3 API introduced in #219.

**Comment by BloggerBust** [comment]
@VincentTam,

Yes, the guide definitely needs an update. I have been busy all summer. I will get caught up with things in the next week or so. Is the latest in upstream master functioning for v3 now? Or is that a problem that is yet to be solved?

@jimmyangel,

[I responded to your comment on my blog](https://bloggerbust.ca/post/staticman-with-github-and-zeit-now-part-3/#Comments) with some instructions on how to obtain some useful logs to help you troubleshoot the issue.

Cheers!

Trevor

**Comment by VincentTam** [comment]
> Is the latest in upstream master functioning for v3 now?

I'm not keen on the recent addition of GitHub Apps support since this bundles Staticman with the proprietary service.  As a result, I regret that I can't respond to your question.

**Comment by jimmyangel** [comment]
Hi @BloggerBust,

I left a comment on your blog! I was able to make it work, thanks a lot for your detailed instructions.

For anyone trying to do this, if you are coming from an earlier deployment (like the original api.staticman.net), do not forget to re-encrypt all your encrypted site configuration (staticman.yml) parameters (like your reCaptcha secret). Otherwise the decrypt will fail silently and you will get a 500 error with no details.

BTW, that ZEIT service looks pretty darn good.

Thanks again,

Ricardo

**Comment by deadlydog** [comment]
I had the same issue recently @jimmyangel and mentioned it in issue #108 and created PR #308 to address it. I'm glad you were able to get it figured out :) 👍

**Comment by BloggerBust** [comment]
> I'm not keen on the recent addition of GitHub Apps support since this bundles Staticman with the proprietary service.

I am empathetic to your sentiment and yet we both have GitHub accounts :-P. I am hoping to move [to sourcehut](https://sourcehut.org/) in the future, but in the meantime I am happy to help improve Staticman for GitHub.

**Comment by BloggerBust** [comment]
@jimmyangel

I saw that this morning. That is great news!

**Comment by alexwaibel** [comment]
This seems resolved. Feel free to comment if it isn't and I'll reopen this.
