### ISSUE TITLE
Extra _id parameter appears in staticman Pull Requests

### ISSUE THREAD

**Issue by sachin10101998** [eduardoboucas/staticman#303]
Whenever Staticman sends a pull request, it adds an `_id `parameter in it irrespective of the type of file it is creating.
For example in[ this Pull Request](https://github.com/sachin10101998bot/aima-exercises/pull/6/files) , `_id: 54023b70-a37e-11e9-9e5a-db49bdb8d58e` parameter is created, along with Email, Name, Message and Date.
Is there some way to remove it from being added in all the Staticman PRs.
Any help would be highly appreciated.

**Comment by sachin10101998** [comment]
@VincentTam

**Comment by VincentTam** [comment]
This field is useful in many situations, notably for Staticman integration in static blog themes.  See, for example, [Minimo's template](https://github.com/MunifTanjim/minimo/blob/4f6e0e9fe8843faa78f602b128f7c8beab2f9c94/layouts/partials/comments/staticman/comment.html#L4).  If you don't like that, you've the freedom to change the code that powers your API instance.  That's a great aspect of open-source solutions that many developers enjoy.  I'm not yet a developer though.  Btw, you might consider [applying MD5 on input email](https://staticman.net/docs/configuration#transforms), so that the email addresses aren't directly committed into your GitHub repo.

**Comment by alexwaibel** [comment]
Expected behavior.
