### ISSUE TITLE
staticmanapp 404 on GitHub?

### ISSUE THREAD

**Issue by JackLiar** [eduardoboucas/staticman#306]
https://github.com/staticmanapp is 404 now on GitHub......

**Comment by nazavode** [comment]
When looking for @staticmanapp user in the "Add collaborators" settings form, I got a "staticmanapp isn’t a GitHub member" error message.

**Comment by lcron** [comment]
Are they banned because they operate too frequently?

**Comment by VincentTam** [comment]
> Are they banned because they operate too frequently?

You may refer to #298.

**Comment by simoniz0r** [comment]
Someone should really update the instructions on  the website to match this...

[quote link](https://github.com/eduardoboucas/staticman/issues/243#issuecomment-453754860)
> Hi all.
> 
> I had a go at implementing Staticman as a GitHub App, which should fix many of the issues people are seeing at the moment. Can I ask for some volunteers to help me test it? Here's how:
> 
> 1. Remove `staticmanapp` as a collaborator
> 2. Go to https://github.com/apps/staticman-net and install the application on your repository
> 3. Submit a comment to the new `v3` endpoint, using `dev.staticman.net` as the base URL – i.e. [https://dev.staticman.net/v3/entry/github/[USERNAME]/[REPOSITORY]/[BRANCH]](https://dev.staticman.net/v3/entry/github/%5BUSERNAME%5D/%5BREPOSITORY%5D/%5BBRANCH%5D)
> 
> Any help is much appreciated.

**Comment by VincentTam** [comment]
> Someone should really update the instructions on the website to match this...

@simoniz0r Your request echoes #271.  Btw, the URL in the 3rd step gives rise to issue #278.  View the project owner's advice.

Different users have different needs, #291 provides documentation for deployment to Zeit Now, whereas #293 asks for info about GitLab integration.  #289 fixes the display problem of tables reported in #90.  Different deployment procedures leads to different steps, and different people are using different versions of the Node.JS app, say @staticmanaima and @Bloggerbust-bot are still using v2.

There's no denying that the current docs are outdated, due to the problem mentioned in the first post in this thread.  For documenting v3, #219 would provide a great source of info.

Some docs about Staticman v3 that I've contributed to:

1. https://mmistakes.github.io/minimal-mistakes/docs/configuration/#static-based-comments-via-staticman
2. https://github.com/daattali/beautiful-jekyll/#staticman-comments
3. https://github.com/onweru/hugo-swift-theme#staticman-comments

**Comment by ghost** [comment]
staticmanapp user can't be found

**Comment by Tautorn** [comment]
staticmanapp isn't a Github member

**Comment by alexwaibel** [comment]
Known issue. See #317

**Comment by sahyagiri** [comment]
> 
> 
> Someone should really update the instructions on the website to match this...
> 
> [quote link](https://github.com/eduardoboucas/staticman/issues/243#issuecomment-453754860)
> 
> > Hi all.
> > I had a go at implementing Staticman as a GitHub App, which should fix many of the issues people are seeing at the moment. Can I ask for some volunteers to help me test it? Here's how:
> > 
> > 1. Remove `staticmanapp` as a collaborator
> > 2. Go to https://github.com/apps/staticman-net and install the application on your repository
> > 3. Submit a comment to the new `v3` endpoint, using `dev.staticman.net` as the base URL – i.e. [https://dev.staticman.net/v3/entry/github/[USERNAME]/[REPOSITORY]/[BRANCH]](https://dev.staticman.net/v3/entry/github/%5BUSERNAME%5D/%5BREPOSITORY%5D/%5BBRANCH%5D)
> > 
> > Any help is much appreciated.
Tried this and got this error 
![image](https://user-images.githubusercontent.com/8480235/90419305-03d1ef80-e0d4-11ea-886b-1ac30ab13d94.png)

**Comment by sahyagiri** [comment]
> 
> 
> Someone should really update the instructions on the website to match this...
> 
> [quote link](https://github.com/eduardoboucas/staticman/issues/243#issuecomment-453754860)
> 
> > Hi all.
> > I had a go at implementing Staticman as a GitHub App, which should fix many of the issues people are seeing at the moment. Can I ask for some volunteers to help me test it? Here's how:
> > 
> > 1. Remove `staticmanapp` as a collaborator
> > 2. Go to https://github.com/apps/staticman-net and install the application on your repository
> > 3. Submit a comment to the new `v3` endpoint, using `dev.staticman.net` as the base URL – i.e. [https://dev.staticman.net/v3/entry/github/[USERNAME]/[REPOSITORY]/[BRANCH]](https://dev.staticman.net/v3/entry/github/%5BUSERNAME%5D/%5BREPOSITORY%5D/%5BBRANCH%5D)
> > 
> > Any help is much appreciated.

This is working fine with minimal mistakes. I will post a detailed step soon! 
Thanks a lot for this fix

**Comment by alexwaibel** [comment]
@sahyagiri that solution utilizes the public instance of Staticman which is not very reliable. Though it involves more work, I would highly advise you follow the guides at the bottom of the README and configure your own instance of Staticman on Heroku. Otherwise, your comments may frequently fail to post to your site.
