### ISSUE TITLE
Detail Guide for Github Staticman App

### ISSUE THREAD

**Issue by wini3d** [eduardoboucas/staticman#310]
Is there a detailed guide on how to use app? I'm using Jekyll and plan to switch from the collaborator to the app.

Followed every steps below:

> 1. Remove staticmanapp as a collaborator
> 2. Go to https://github.com/apps/staticman-net and install the application on your repository
> 3. Submit a comment to the new v3 endpoint, using dev.staticman.net as the base URL – i.e. https://dev.staticman.net/v3/entry/github/[USERNAME]/[REPOSITORY]/[BRANCH]

Getting a 400 "Invalid Version" error when using the post action below
`https://dev.staticman.net/v3/entry/github/[USERNAME]/[REPOSITORY]/[BRANCH]`

**Comment by jannispaul** [comment]
I don't think the app is reliable or even working anymore at this point... What I have read and then done myself is to clone the repo and create a Heroku app from it so you have your own instance. 

I have collected a couple of the tutorials and made my own instructions based on them in this gist: https://gist.github.com/jannispaul/3787603317fc9bbb96e99c51fe169731

Hope that helps =)

**Comment by wini3d** [comment]
Thank you for this detailed self hosted guide @jannispaul ! :D appreciate it. I will dive into this soon and get back in case I got questions if that is ok.

**Comment by VincentTam** [comment]
@jannispaul @wini3d Note that the linked gist, which has made a reference to [my GitLab setup guide](https://vincenttam.gitlab.io/post/2018-09-16-staticman-powered-gitlab-pages/1/), is using the legacy authentication method, due to the presence of `GITHUB_TOKEN`, which is assigned to a GitHub user.

Therefore, the linked gist is *not* answering the question at all.

> Is there a detailed guide on how to use app?

> I'm using Jekyll and plan to switch from the collaborator to the app.

Whether you use Jekyll is irrelevant here, since Staticman doesn't care that, as the author has clarified in https://github.com/eduardoboucas/staticman/issues/264#issuecomment-460446511.

**Comment by wini3d** [comment]
Hi @VincentTam thank you for the info. Yes, at some point I would also consider hosting on gitlab pages and would be interested in using staticman as well. 

I have not yet tried out my own hosting/instance other than using publicly available servers like the collaborator staticmanlab which points to the herokuapp. I take it that the latest version of staticman would work on any setup, or are there still issues and would require specific guide?

It would be also nice to have a straightforward setup with Heroku (one click) and Dokku if possible, just a thought.

**Comment by VincentTam** [comment]
> I take it that the latest version of staticman would work on any setup, or are there still issues and would require specific guide?

@wini3d I've never (and I won't) use the lastest GitHub Apps version (for reasons detailed iin my earlier comment https://github.com/eduardoboucas/staticman/issues/299#issuecomment-508029359), and I don't know any guide about that.

Since you ask for issues about the lastest version, there's one thing I can be sure: spam issue still concerns the GitHub Apps version.  See the following repo for an example:
https://github.com/zinefer/zinefer.github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3ASpam

Actually, the quoted instructions on the top is detailed enough.  You just need to replace `dev` with `api` due to https://github.com/eduardoboucas/staticman/issues/278#issuecomment-475170669.

> It would be also nice to have a straightforward setup with Heroku (one click) and Dokku if possible, just a thought.

Support for Heroku deploy button has already been requested in #305.  I'd be glad to see a PR for the deploy button.

**Comment by wini3d** [comment]
Thanks a lot @VincentTam So, it's just replacing `dev` with `api` for the GitHub App to work. Somehow that instruction got buried there with the other details. I will try this again.

> Support for Heroku deploy button has already been requested in #305. I'd be glad to see a PR for the deploy button.

Great and good to know.

**Comment by wini3d** [comment]
@VincentTam I see now what you mean on moving forward past the GitHub App. I'm currently getting Error 429 and that equals to "too many requests" if I'm not mistaken, which I had no problem with staticmanlab.

Closing this now with the steps below:

1. Remove staticmanapp as a collaborator
2. Go to https://github.com/apps/staticman-net and install the application on your repository
3. Submit a comment to the new v3 endpoint, using api.staticman.net as the base URL – i.e. https://api.staticman.net/v3/entry/github/[USERNAME]/[REPOSITORY]/[BRANCH]/properties

**Comment by VincentTam** [comment]
@wini3d I'm sorry for eating my words said one and a half years ago.  Thanks to https://hajekj.net/2020/04/15/staticman-setup-in-app-service/, I has provided an illustrated API setup guide: https://github.com/pacollins/hugo-future-imperfect-slim/wiki/staticman.yml.

**Comment by wini3d** [comment]
no problem and thanks for the added info!
