### ISSUE TITLE
An error occured. [INVALID_FIELDS] when replying to a comment

### ISSUE THREAD

**Issue by Vel-San** [eduardoboucas/staticman#354]
~~Hi! I've installed and configured staticman in my site and it's working perfectly, except king of 2 things:

- When i click on a reply to for a comment and click submit after filling the fields, i get the error

An error occured.
[INVALID_FIELDS]

Any idea why this would happen? I have 'email' field set to not be required as a parameter. I tried to look this up but couldn't find anything for it.~~ 

Fixed.

_____

- Another issue is mailgun and email subscriptions. Mailgun is no longer free which makes the documentation kind of redundant unless we pay and make a custom domain. Will there be any change to this? I followed several guides but it simply didn't work with the sandbox domain because it's for testing only.

**Comment by alexwaibel** [comment]
Glad it appears you were able to resolve your `INVALID_FIELDS` error. Regarding Mailgun, there's some good discussion in #353 about the cost. In practice it seems the Mailgun pricing is quite fair and I unfortunately have no time at the moment to explore alternatives.

Marking this closed as the issue seems to be resolved. Feel free to ask any followup questions here though.
