### ISSUE TITLE
Question: How to reverse transformations 

### ISSUE THREAD

**Issue by sirinath** [eduardoboucas/staticman#358]
If I say add:

```
transforms:
  email: "md5" # The email field will be MD5-hashed
```

How do I retrieve the actual email?

**Comment by jayliu50** [comment]
Then you just leave out the email field from the transforms, and it will come across in plaintext.

**Comment by alexwaibel** [comment]
There is no way to reverse an md5 hash afaik. I'm going to mark this as closed since the question has been answered but feel free to ask any follow up questions here.

**Comment by sirinath** [comment]
If there is no way to retrieve the original field what is the purpose of `transforms` as in:

```
transforms:
  email: "md5" # The email field will be MD5-hashed
```

**Comment by alexwaibel** [comment]
IIRC the point of this transform is so that one can still submit an email with a comment so that if that Staticman instance has mailgun set up the commenter can get email notifications. The md5 transform is then used when Staticman submits the PR for the comment so that user emails aren't shown in plaintext on the GH repo.

**Comment by willymcallister** [comment]
I have the same question. MD5 hashing is specified in staticman.yml. The Staticman instance (mine is at Heroku) uses MD5 for two things.
1. Staticman receives the comment_form and concatenates three fields, separated by hyphens: username-repository (options[parent])-entryID (article URL). The result is hashed to produce a 32 text character name for the mailing list for that post. That name is sent to Mailgun with a request to create the mailing list.
2. The subscriber's email is sent to Staticman instance as cleartext, included in the comment_form submission. Staticman sends the cleartext email address to Mailgun to become an entry in a mailing list in my secure account at MailGun. 
3. Staticman does an MD5 hash of the email address and returns the result as part of the PR. It gets saved in _data/comments/post-name/comment-file.yml in my publicly-accessible repository at GitHub.  

I'm not sure why Staticman bothers with 3., since there's not really anything I can do with the hashed email address. It was perhaps envisioned as a future flexibility when first implemented. One thing you might do is answer the question, "Has this person ever emailed me before?" If you MD5 hash a newly arrived email address and its hash matches one you already have in your repository, then the answer is "yes". 

My notes on Staticman at Heroku: https://spinningnumbers.org/a/staticman-heroku.html

**Comment by pingu8007** [comment]
> I'm not sure why Staticman bothers with 3., since there's not really anything I can do with the hashed email address.

If you use Gravatar you can show visitor's avatar with those hashed email. Gravatar use md5-hashed email as identifier.
