### ISSUE TITLE
Feature request: Allow other version control systems

### ISSUE THREAD

**Issue by dertuxmalwieder** [eduardoboucas/staticman#385]
Not everyone uses Git, so it might make sense to allow defining an arbitrary command to be called *instead* of the GitHub/GitLab transaction.

**Comment by pingu8007** [comment]
Is the version control system you want to support
- has an API to retrieve a single file without clone? (Used to acquire `staticman.yml`)
- has an API to append a single file without clone? (Used to insert comments)

Instead of using regular git operation, Staticman makes use of GitHub/GitLab's API to minimum the data traffic. If the target version control system can't do that, Staticman will have to clone everything again and again. It will dramatically increase the complexity (as well as storage and traffic) and I can't image how can Staticman achieve it without rewrite from scratch.

This project is silent for months, fell free to create your forks.

**Comment by dertuxmalwieder** [comment]
I understand. In that case, this suggestion makes less sense than I was hoping.
