### ISSUE TITLE
Documentation for generated fields, transforms and formats

### ISSUE THREAD

**Issue by eduardoboucas** [eduardoboucas/staticman#56]
New sections on https://staticman.net/docs describing all the supported generated fields, transforms and formats.

**Comment by zburgermeiszter** [comment]
Please add some documentation for how to generate RSA keys when installing it on VPS. Thanks.

**Comment by eduardoboucas** [comment]
As mentioned by @dansmith65:

> I think https://staticman.net/docs/configuration#generatedFields should state the available types and options, for example:
>
> date options format:
> - "timestamp": milliseconds since 1970/01/01
> - "timestamp-seconds": seconds since 1970/01/01
> - "iso8601": date as a string like: '2017-03-03T23:28:14.272Z'

I think we should add a new page to [the docs](https://staticman.net/docs/) for generated fields and another one for all the available options (e.g. `redirect`).

If anyone wants to help with this, here's the repository for the site: https://github.com/eduardoboucas/staticman.net

**Comment by dansmith65** [comment]
I did spend some time trying to figure out how the docs site works, but wasn't clear on it, so I decided to post an issue instead of a pull request.

It seems to me like the content of the docs site comes from: https://github.com/eduardoboucas/staticman.net/tree/master/_data, which is created by https://github.com/eduardoboucas/staticman.net/blob/master/utils/generateDocs.js, which I'm guessing get's it's data from https://github.com/eduardoboucas/staticman/blob/master/siteConfig.js. Is that correct?

If so, what do you use to create https://github.com/eduardoboucas/staticman/blob/master/siteConfig.js? Do you just manually create that file? Or did I miss something?

**Comment by eduardoboucas** [comment]
The JSON files within `_data` are generated by running `utils/generateDocs.js` like this:

```
node utils/generateDocs.js --path=path/to/staticman
```

But those only extract information from the API config schema (`config.js`) and the site config schema (`siteConfig.js`), both using [convict](https://github.com/mozilla/node-convict).

For the generated fields, I think a static page is appropriate, since we don't really have a way of pulling those from the codebase to generate the docs automatically.

Does that make sense?

**Comment by eduardoboucas** [comment]
Live at https://staticman.net/docs/generated-fields.
